### ISSUE TITLE
today's cases/deaths in the US are the total, not just today's

### ISSUE THREAD

**Issue by kevacarr** [gorkang/2020-corona#33]
When I set for just USA, cases, daily, not log - or for just USA, deaths, daily, not log - I get basically a straight line and then a huge jump for the most recent day, because the "most recent day" number is being mistakenly entered as the "total for all days" . This only happened a week or two ago, before that it was working better.

**Comment by gorkang** [comment]
Thanks for the heads up. It seems the JHU data stopped updating a couple of weeks ago. Will take a look in the next few days.

**Comment by kevacarr** [comment]
I’d really appreciate it! Thank you! I love the way you show everything.

Karen

**Comment by gorkang** [comment]
OK, it's working now. I switched to Our World in Data because the JHU API seems to be charging for access.

Thanks for reporting this!

**Comment by kevacarr** [comment]
I’m sorry to do this to you, but the US tracker has stopped working again, about a week or two ago. Might be misleading, the way it is. Plus, I love this tool and would like to keep using it!

thanks for all your work, 

best,

Karen Carr

**Comment by gorkang** [comment]
No worries. On the contrary, thanks for letting me know!

Should be updating regularly again now.

**Comment by kevacarr** [comment]
Oh, thank you! It’s working properly now. 

Karen
